### ISSUE TITLE
AttributeError("can't set attribute")

### ISSUE THREAD

**Issue by Evdokimoff** [djsudduth/keep-it-markdown#26]
I trying to use KIM 0.40. Successfully logged, successfully run test, but further I have a problem: Problem with markdown file creation: mdfiles\somefile.md  Technical Error Message: AttributeError("can't set attribute") I see that error appears with notes contains pictures (maybe other objects). Further I delete pictures in Keep - I don't see any error. But I have thousands of notes... What can I do with it?

**Comment by djsudduth** [comment]
@Evdokimoff hi! Can you explain to me what type of note causes the issue?  What do you have within the note? (or can you post an image of the note - if it isn't personal - that has the problem)?  I'm working on bug fixes right now for 0.4.1 so it would be great if I can fix it.

**Comment by Evdokimoff** [comment]
One of this note, for example, contains just one photo and some bullets
(picture attached). In other note were two pictures and bullets


ср, 5 мая 2021 г. в 01:02, Don Sudduth ***@***.***>:

**Comment by djsudduth** [comment]
It doesn't look like the image attached - can you try again?

**Comment by djsudduth** [comment]
@Evdokimoff also, what device and OS did you use to create the notes with images?  Was it a mobile device?  (Also wondering if the bullets could be the problem)

**Comment by Evdokimoff** [comment]
<img width="285" alt="Screenshot (3)" src="https://user-images.githubusercontent.com/3206382/117104834-80e9e580-ad85-11eb-8410-023da094013e.png">

Maybe I used mobile (Xiaomi Redmi Note 7) and Android for these notes (probability 90%)

**Comment by djsudduth** [comment]
@Evdokimoff - can you tell if the image downloaded into the mdfiles/media folder?  It would have the same title (Обустройство Квартиры0.png or Обустройство Квартиры0.jpg) Also, I see you have check boxes which was something just fixed in 0.4.1 (but, they weren't failing). Did you have tags as well?

If possible, could you copy and paste the list from the note (if it isn't personal) here?  Also, any tags used?  I will try to recreate the note. 

Спасибо!!!

**Comment by djsudduth** [comment]
If you want, you could also share the note to my test Google account ( pluraldon at yahoo.com ). Another way for me to test it.

**Comment by Evdokimoff** [comment]
I gave you access, check it
Yes, image is downloaded with 0 at the end
Yes, I have check boxes and tags

ср, 5 мая 2021 г., 18:18 Don Sudduth ***@***.***>:

**Comment by djsudduth** [comment]
The share didn't work - I don't see it in the test account

**Comment by Evdokimoff** [comment]
Check again :)

ср, 5 мая 2021 г., 20:41 Don Sudduth ***@***.***>:

**Comment by djsudduth** [comment]
@Evdokimoff - thank you for sharing that!!! I found the problem. It had already been fixed in 0.4.1. Turns out it is this same issue -> https://github.com/djsudduth/keep-it-markdown/issues/22.  If you want you can go here to the develop branch and just replace your 0.4.0 Kim.py with the new develop testing Kim.py file for 0.4.1.

https://github.com/djsudduth/keep-it-markdown/tree/develop

The new release should be out soon.

**Comment by Evdokimoff** [comment]
Thanks a lot! I "update" KIM - it's working! Thank for you work! Спасибо ;)
