### ISSUE TITLE
unable to input info when prompted

### ISSUE THREAD

**Issue by WisnetSaga** [djsudduth/keep-it-markdown#80]
whenever i run the "get-token.py" script, it runs however doesnt let me input anything as it just runs & assumes "done"

**im on mac os, using mainly the default mac os terminal, tried using the python launcher, still does the same thing. im on a high enough python3 version.**

```cd '/Users/wisnet/Downloads/keep-it-markdown-0.6.0/' && '/usr/local/bin/python3' -i  '/Users/wisnet/Downloads/keep-it-markdown-0.6.0/get_token.py'  && echo Exit status: $? && exit 1
wisnet@Wisnets-Air ~ % cd '/Users/wisnet/Downloads/keep-it-markdown-0.6.0/' && '/usr/local/bin/python3' -i  '/Users/wisnet/Downloads/keep-it-markdown-0.6.0/get_token.py'  && echo Exit status: $? && exit 1

Enter your Google ID, the copied oauth_token cookie, and any value for the Android ID:


Either you entered your ID and OAuth cookie incorrectly or the OAuth cookie has expired. Try getting the OAuth cookie and run this again - the cookie expires within 5 minutes.
>>>

**Comment by djsudduth** [comment]
@WisnetSaga you need to run the script in interactive mode - don't use the launcher. Just go to terminal and run it directly.

**Comment by djsudduth** [comment]
@WisnetSaga you need to run Terminal from the Mac applications menu. Then, once you're in the terminal window session, run the script I noted by typing it in directly and pressing enter. 

This assumes you have a new, clean Python environment via a fresh install of python or a new virtual environment on your Mac with the gpsoauth package installed via the instructions. If you don't know how to do that then you can install Docker on your Mac and run the Docker image. That will create a clean virtual machine and environment to get the Keep token (see the readme on running Docker).

**Comment by djsudduth** [comment]
@WisnetSaga - I just tried it on my Mac. I think I see the issue you're having. If you haven't installed the lastest `gpsoauth` in your python packages, then the get_token.py script will fail to prompt you as you noted above. 

To fix this, in a clean venv or new python install, run this command that's in the README:
`pip install git+https://github.com/simon-weber/gpsoauth.git@8a5212481f80312e06ba6e0a29fbcfca1f210fd1`
(be sure you installed git)

The prompts for your ID, OAuth and Android ID will only show up after you install that module - otherwise the script fails without prompting you.

**Comment by djsudduth** [comment]
Assuming fixed - closing
